#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 25, 2024 05:08:39 PM IST  platform: Linux

import tkinter as tk
from inspect import getsourcefile
from os.path import dirname

from tkinterdnd2 import TkinterDnD

import bank_statement_utility.ui.bankstatementutility as bankstatementutility
from bank_statement_utility.config import config
from bank_statement_utility.logger import log
from bank_statement_utility.version import __version__

_debug = True  # False to eliminate debug printing from callback functions.


def main(*args):
    """
    Main entry point for the application.
    """
    global root
    root = TkinterDnD.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)

    # Setting icon of master window
    execution_path = dirname(getsourcefile(lambda: 0))
    p1 = tk.PhotoImage(file=execution_path + '/icon.png')
    root.iconphoto(False, p1)

    log.info(config['Basic']['appname'] + " version: " + __version__)

    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = bankstatementutility.MainScreenView(_top1)
    root.mainloop()


if __name__ == '__main__':
    main()
